/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Revision;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Edison
 */
public class ViewCrudRevision extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCrudRevision
     */
    public ViewCrudRevision() {
        initComponents();
    }

    public JButton getBttnImprimir() {
        return bttnImprimir;
    }

    public void setBttnImprimir(JButton bttnImprimir) {
        this.bttnImprimir = bttnImprimir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogMascota = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Pacientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btn_AgregarMas = new javax.swing.JButton();
        DialogVeterinario = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Veterinario = new javax.swing.JTable();
        txtBuscar1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btn_AgregarMed = new javax.swing.JButton();
        dlgRevision = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdmascotaRev = new javax.swing.JTextField();
        txtIdclienteRev = new javax.swing.JTextField();
        txtNombreMRev = new javax.swing.JTextField();
        txtRazaRev = new javax.swing.JTextField();
        txtSexoRev = new javax.swing.JTextField();
        txtEspecieRev = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblFotoMascotaRev = new javax.swing.JLabel();
        btnBuscarMasc = new javax.swing.JButton();
        lb_MascotaR = new javax.swing.JLabel();
        txt_ColorRev = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_IDVet = new javax.swing.JTextField();
        txt_NomVet = new javax.swing.JTextField();
        txt_ApellidoVet = new javax.swing.JTextField();
        txt_EspecialidadVet = new javax.swing.JTextField();
        btnBuscarMed = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lb_VeterinarioR1 = new javax.swing.JLabel();
        btnAgregarRev = new javax.swing.JButton();
        btnLimpiarRev = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txt_enfermedad = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt_Descripcion = new javax.swing.JTextArea();
        lb_DiagnosticoR = new javax.swing.JLabel();
        lb_DescripcionR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdfacturaRev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaRev = new javax.swing.JTextField();
        dlgReporteRevision = new javax.swing.JDialog();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnReporteImprimir = new javax.swing.JButton();
        txtReporteIdMedico = new javax.swing.JTextField();
        txtReporteMascota = new javax.swing.JTextField();
        txtReporteNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRev = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        CBFechas = new javax.swing.JComboBox<>();
        BusquedaFecha = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        bttnImprimir = new javax.swing.JButton();
        btnCrearRev = new javax.swing.JButton();
        btnEliminarRev = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        DialogMascota.setBackground(new java.awt.Color(255, 255, 255));
        DialogMascota.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(126, 197, 68));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/salud.png"))); // NOI18N
        jLabel20.setText("PACIENTES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CI Cliente", "Nombre", "Sexo", "Especie", "Raza", "Color", "Edad", "Fecha Ingreso", "Foto"
            }
        ));
        jScrollPane2.setViewportView(Tabla_Pacientes);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel21.setText("BUSCAR:");

        btn_AgregarMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar-archivo.png"))); // NOI18N
        btn_AgregarMas.setText("Añadir");
        btn_AgregarMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_AgregarMas)
                        .addGap(46, 46, 46))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_AgregarMas))
                    .addComponent(jLabel21))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout DialogMascotaLayout = new javax.swing.GroupLayout(DialogMascota.getContentPane());
        DialogMascota.getContentPane().setLayout(DialogMascotaLayout);
        DialogMascotaLayout.setHorizontalGroup(
            DialogMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogMascotaLayout.setVerticalGroup(
            DialogMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogMascotaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DialogVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        DialogVeterinario.setResizable(false);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(126, 197, 68));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/veterinario.png"))); // NOI18N
        jLabel22.setText("VETERINARIO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Veterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Veterinario", "Nombre_Veterinario", "Apellido_Veterinario", "Direccion_Veterinario", "Especialidad"
            }
        ));
        jScrollPane3.setViewportView(tbl_Veterinario);

        jLabel23.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel23.setText("BUSCAR:");

        btn_AgregarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar-archivo.png"))); // NOI18N
        btn_AgregarMed.setText("Añadir");
        btn_AgregarMed.setBorderPainted(false);
        btn_AgregarMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AgregarMed)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AgregarMed)
                    .addComponent(jLabel23))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogVeterinarioLayout = new javax.swing.GroupLayout(DialogVeterinario.getContentPane());
        DialogVeterinario.getContentPane().setLayout(DialogVeterinarioLayout);
        DialogVeterinarioLayout.setHorizontalGroup(
            DialogVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogVeterinarioLayout.setVerticalGroup(
            DialogVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogVeterinarioLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dlgRevision.setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/mascota-amigable.png"))); // NOI18N
        jLabel4.setText("Mascota");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("ID MASCOTA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("ID CLIENTE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("NOMBRE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText("RAZA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel10.setText("SEXO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel11.setText("ESPECIE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel12.setText("COLOR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));
        jPanel1.add(txtIdmascotaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, -1));
        jPanel1.add(txtIdclienteRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));
        jPanel1.add(txtNombreMRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));
        jPanel1.add(txtRazaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, -1));
        jPanel1.add(txtSexoRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, -1));
        jPanel1.add(txtEspecieRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel13.setText("EDAD");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        lblFotoMascotaRev.setBackground(new java.awt.Color(0, 0, 0));
        lblFotoMascotaRev.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblFotoMascotaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 170));

        btnBuscarMasc.setText("...");
        btnBuscarMasc.setBorderPainted(false);
        btnBuscarMasc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 36, -1));

        lb_MascotaR.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_MascotaR.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lb_MascotaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, 20));
        jPanel1.add(txt_ColorRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, -1));
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 210, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("ID VETERINARIO");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel15.setText("NOMBRE");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel16.setText("APELLIDO");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel18.setText("ESPECIALIDAD");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel3.add(txt_IDVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));
        jPanel3.add(txt_NomVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 200, -1));
        jPanel3.add(txt_ApellidoVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 200, -1));
        jPanel3.add(txt_EspecialidadVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 200, -1));

        btnBuscarMed.setText("...");
        btnBuscarMed.setBorderPainted(false);
        btnBuscarMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnBuscarMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 32, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/veterinario.png"))); // NOI18N
        jLabel19.setText("Veterinario");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lb_VeterinarioR1.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_VeterinarioR1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(lb_VeterinarioR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 120, 20));

        btnAgregarRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar.png"))); // NOI18N
        btnAgregarRev.setText("Agregar");
        btnAgregarRev.setBorderPainted(false);
        btnAgregarRev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLimpiarRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/codigo-limpio.png"))); // NOI18N
        btnLimpiarRev.setText("LIMPIAR");
        btnLimpiarRev.setBorderPainted(false);
        btnLimpiarRev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Txt_enfermedad.setColumns(20);
        Txt_enfermedad.setRows(5);
        jScrollPane4.setViewportView(Txt_enfermedad);

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel24.setText("DESCRIPCIÓN");

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel25.setText("DIAGNÓSTICO");

        Txt_Descripcion.setColumns(20);
        Txt_Descripcion.setRows(5);
        jScrollPane5.setViewportView(Txt_Descripcion);

        lb_DiagnosticoR.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_DiagnosticoR.setForeground(new java.awt.Color(255, 51, 51));

        lb_DescripcionR.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_DescripcionR.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("ID REVISION");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setText("FECHA:");

        javax.swing.GroupLayout dlgRevisionLayout = new javax.swing.GroupLayout(dlgRevision.getContentPane());
        dlgRevision.getContentPane().setLayout(dlgRevisionLayout);
        dlgRevisionLayout.setHorizontalGroup(
            dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRevisionLayout.createSequentialGroup()
                .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgRevisionLayout.createSequentialGroup()
                        .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgRevisionLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dlgRevisionLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(9, 9, 9)
                                        .addComponent(txtIdfacturaRev, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel2)
                                        .addGap(19, 19, 19)
                                        .addComponent(txtFechaRev, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(dlgRevisionLayout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(btnAgregarRev)
                                        .addGap(62, 62, 62)
                                        .addComponent(btnLimpiarRev))))
                            .addGroup(dlgRevisionLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(lb_DescripcionR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgRevisionLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_DiagnosticoR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgRevisionLayout.createSequentialGroup()
                        .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        dlgRevisionLayout.setVerticalGroup(
            dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRevisionLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dlgRevisionLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgRevisionLayout.createSequentialGroup()
                        .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtIdfacturaRev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtFechaRev, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(lb_DescripcionR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_DiagnosticoR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlgRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarRev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarRev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dlgReporteRevision.setResizable(false);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        jLabel14.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 204, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/seo.png"))); // NOI18N
        jLabel14.setText("Parametros para Imprimir");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel17.setText("Buscar por:");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 17, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        jLabel27.setText("Id Medico:");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        jLabel31.setText("Id Mascota:");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Arial", 3, 13)); // NOI18N
        jLabel32.setText("Nombre:");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/pugbuscar.png"))); // NOI18N
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 180, -1));

        btnReporteImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/impresion.png"))); // NOI18N
        btnReporteImprimir.setText("Imprimir");
        btnReporteImprimir.setBorderPainted(false);
        btnReporteImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(btnReporteImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));
        jPanel13.add(txtReporteIdMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 156, -1));
        jPanel13.add(txtReporteMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 156, -1));
        jPanel13.add(txtReporteNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 156, -1));

        javax.swing.GroupLayout dlgReporteRevisionLayout = new javax.swing.GroupLayout(dlgReporteRevision.getContentPane());
        dlgReporteRevision.getContentPane().setLayout(dlgReporteRevisionLayout);
        dlgReporteRevisionLayout.setHorizontalGroup(
            dlgReporteRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgReporteRevisionLayout.setVerticalGroup(
            dlgReporteRevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteRevisionLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setClosable(true);
        setIconifiable(true);
        setTitle("Revision");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/7x16.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(251, 118, 33));
        jPanel2.setForeground(new java.awt.Color(244, 244, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaRev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID REVISION", "ID MEDICO", "ID MASCOTA", "NOMBRE", "FECHA ", "DESCRIPCION", "DIAGNOSTICO"
            }
        ));
        TablaRev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(TablaRev);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 830, 200));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Buscar:");

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/informacion.png"))); // NOI18N
        jLabel35.setToolTipText("Ingrese en el cuadro de busqueda el ID de la revision o Nombre del Paciente o ID del Medico");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(21, 21, 21))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 300, 80));

        jLabel30.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("FILTROS DE BUSQUEDA");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBFechas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar", "-Todos los registros", "-Buscar por fecha" }));
        jPanel10.add(CBFechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        jPanel10.add(BusquedaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 144, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Buscar:");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/lupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 50, 40));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 290, 80));

        bttnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/impresion.png"))); // NOI18N
        bttnImprimir.setText("Imprimir");
        bttnImprimir.setBorderPainted(false);
        bttnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(bttnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 40));

        btnCrearRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar.png"))); // NOI18N
        btnCrearRev.setText("Crear");
        btnCrearRev.setToolTipText("");
        btnCrearRev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnCrearRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        btnEliminarRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/basura.png"))); // NOI18N
        btnEliminarRev.setText("Eliminar");
        btnEliminarRev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnEliminarRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(126, 197, 68));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/buscando.png"))); // NOI18N
        jLabel3.setText("Revision");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCrearRev() {
        return btnCrearRev;
    }

    public void setBtnCrearRev(JButton btnCrearRev) {
        this.btnCrearRev = btnCrearRev;
    }

    public JButton getBtnEliminarRev() {
        return btnEliminarRev;
    }

    public JButton getBtnReporteImprimir() {
        return btnReporteImprimir;
    }

    public void setBtnReporteImprimir(JButton btnReporteImprimir) {
        this.btnReporteImprimir = btnReporteImprimir;
    }

    public JDialog getDlgReporteRevision() {
        return dlgReporteRevision;
    }

    public void setDlgReporteRevision(JDialog dlgReporteRevision) {
        this.dlgReporteRevision = dlgReporteRevision;
    }

    public JTextField getTxtReporteIdMedico() {
        return txtReporteIdMedico;
    }

    public void setTxtReporteIdMedico(JTextField txtReporteIdMedico) {
        this.txtReporteIdMedico = txtReporteIdMedico;
    }


    public JTextField getTxtReporteMascota() {
        return txtReporteMascota;
    }

    public void setTxtReporteMascota(JTextField txtReporteMascota) {
        this.txtReporteMascota = txtReporteMascota;
    }

    public JTextField getTxtReporteNombre() {
        return txtReporteNombre;
    }

    public void setTxtReporteNombre(JTextField txtReporteNombre) {
        this.txtReporteNombre = txtReporteNombre;
    }

    public void setBtnEliminarRev(JButton btnEliminarRev) {
        this.btnEliminarRev = btnEliminarRev;
    }

    public JDialog getDlgRevision() {
        return dlgRevision;
    }

    public void setDlgRevision(JDialog dlgRevision) {
        this.dlgRevision = dlgRevision;
    }
    
    
    public JTextArea getTxt_Descripcion() {
        return Txt_Descripcion;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JLabel getLb_DescripcionR() {
        return lb_DescripcionR;
    }

    public void setLb_DescripcionR(JLabel lb_DescripcionR) {
        this.lb_DescripcionR = lb_DescripcionR;
    }

    public JTextField getTxt_Buscar() {
        return txt_Buscar;
    }

    public JDateChooser getBusquedaFecha() {
        return BusquedaFecha;
    }

    public void setBusquedaFecha(JDateChooser BusquedaFecha) {
        this.BusquedaFecha = BusquedaFecha;
    }

    public JComboBox<String> getCBFechas() {
        return CBFechas;
    }

    public void setCBFechas(JComboBox<String> CBFechas) {
        this.CBFechas = CBFechas;
    }

    public void setTxt_Buscar(JTextField txt_Buscar) {
        this.txt_Buscar = txt_Buscar;
    }

    public JLabel getLb_DiagnosticoR() {
        return lb_DiagnosticoR;
    }

    public void setLb_DiagnosticoR(JLabel lb_DiagnosticoR) {
        this.lb_DiagnosticoR = lb_DiagnosticoR;
    }

    public JLabel getLb_MascotaR() {
        return lb_MascotaR;
    }

    public void setLb_MascotaR(JLabel lb_MascotaR) {
        this.lb_MascotaR = lb_MascotaR;
    }

    public JLabel getLb_VeterinarioR1() {
        return lb_VeterinarioR1;
    }

    public void setLb_VeterinarioR1(JLabel lb_VeterinarioR1) {
        this.lb_VeterinarioR1 = lb_VeterinarioR1;
    }

    public void setTxt_Descripcion(JTextArea Txt_Descripcion) {
        this.Txt_Descripcion = Txt_Descripcion;
    }

    public JTextArea getTxt_enfermedad() {
        return Txt_enfermedad;
    }

    public void setTxt_enfermedad(JTextArea Txt_enfermedad) {
        this.Txt_enfermedad = Txt_enfermedad;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public void setjScrollPane5(JScrollPane jScrollPane5) {
        this.jScrollPane5 = jScrollPane5;
    }

    public JDialog getDialogMascota() {
        return DialogMascota;
    }

    public void setDialogMascota(JDialog DialogMascota) {
        this.DialogMascota = DialogMascota;
    }

    public JDialog getDialogVeterinario() {
        return DialogVeterinario;
    }

    public void setDialogVeterinario(JDialog DialogVeterinario) {
        this.DialogVeterinario = DialogVeterinario;
    }

    public JTable getTablaRev() {
        return TablaRev;
    }

    public void setTablaRev(JTable TablaRev) {
        this.TablaRev = TablaRev;
    }

    public JTable getTabla_Pacientes() {
        return Tabla_Pacientes;
    }

    public void setTabla_Pacientes(JTable Tabla_Pacientes) {
        this.Tabla_Pacientes = Tabla_Pacientes;
    }

    public JButton getBtnAgregarRev() {
        return btnAgregarRev;
    }

    public void setBtnAgregarRev(JButton btnAgregarRev) {
        this.btnAgregarRev = btnAgregarRev;
    }

    public JButton getBtnBuscarMasc() {
        return btnBuscarMasc;
    }

    public void setBtnBuscarMasc(JButton btnBuscarMasc) {
        this.btnBuscarMasc = btnBuscarMasc;
    }

    public JButton getBtnBuscarMed() {
        return btnBuscarMed;
    }

    public void setBtnBuscarMed(JButton btnBuscarMed) {
        this.btnBuscarMed = btnBuscarMed;
    }

    public JButton getBtnLimpiarRev() {
        return btnLimpiarRev;
    }

    public void setBtnLimpiarRev(JButton btnLimpiarRev) {
        this.btnLimpiarRev = btnLimpiarRev;
    }

    public JButton getBtn_AgregarMas() {
        return btn_AgregarMas;
    }

    public void setBtn_AgregarMas(JButton btn_AgregarMas) {
        this.btn_AgregarMas = btn_AgregarMas;
    }

    public JButton getBtn_AgregarMed() {
        return btn_AgregarMed;
    }

    public void setBtn_AgregarMed(JButton btn_AgregarMed) {
        this.btn_AgregarMed = btn_AgregarMed;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JLabel getLblFotoMascotaRev() {
        return lblFotoMascotaRev;
    }

    public void setLblFotoMascotaRev(JLabel lblFotoMascotaRev) {
        this.lblFotoMascotaRev = lblFotoMascotaRev;
    }

    public JTable getTbl_Veterinario() {
        return tbl_Veterinario;
    }

    public void setTbl_Veterinario(JTable tbl_Veterinario) {
        this.tbl_Veterinario = tbl_Veterinario;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public void setTxtBuscar(JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

    public JTextField getTxtBuscar1() {
        return txtBuscar1;
    }

    public void setTxtBuscar1(JTextField txtBuscar1) {
        this.txtBuscar1 = txtBuscar1;
    }

    public JTextField getTxtEspecieRev() {
        return txtEspecieRev;
    }

    public JTextField getTxt_ColorRev() {
        return txt_ColorRev;
    }

    public void setTxt_ColorRev(JTextField txt_ColorRev) {
        this.txt_ColorRev = txt_ColorRev;
    }

    public void setTxtEspecieRev(JTextField txtEspecieRev) {
        this.txtEspecieRev = txtEspecieRev;
    }

    public JTextField getTxtFechaRev() {
        return txtFechaRev;
    }

    public void setTxtFechaRev(JTextField txtFechaRev) {
        this.txtFechaRev = txtFechaRev;
    }

    public JTextField getTxtIdclienteRev() {
        return txtIdclienteRev;
    }

    public void setTxtIdclienteRev(JTextField txtIdclienteRev) {
        this.txtIdclienteRev = txtIdclienteRev;
    }

    public JTextField getTxtIdfacturaRev() {
        return txtIdfacturaRev;
    }

    public void setTxtIdfacturaRev(JTextField txtIdfacturaRev) {
        this.txtIdfacturaRev = txtIdfacturaRev;
    }

    public JTextField getTxtIdmascotaRev() {
        return txtIdmascotaRev;
    }

    public void setTxtIdmascotaRev(JTextField txtIdmascotaRev) {
        this.txtIdmascotaRev = txtIdmascotaRev;
    }

    public JTextField getTxtNombreMRev() {
        return txtNombreMRev;
    }

    public void setTxtNombreMRev(JTextField txtNombreMRev) {
        this.txtNombreMRev = txtNombreMRev;
    }

    public JTextField getTxtEdad() {
        return txtEdad;
    }

    public void setTxtEdad(JTextField txtEdad) {
        this.txtEdad = txtEdad;
    }

    public JTextField getTxtRazaRev() {
        return txtRazaRev;
    }

    public void setTxtRazaRev(JTextField txtRazaRev) {
        this.txtRazaRev = txtRazaRev;
    }

    public JTextField getTxtSexoRev() {
        return txtSexoRev;
    }

    public void setTxtSexoRev(JTextField txtSexoRev) {
        this.txtSexoRev = txtSexoRev;
    }

    public JTextField getTxt_ApellidoVet() {
        return txt_ApellidoVet;
    }

    public void setTxt_ApellidoVet(JTextField txt_ApellidoVet) {
        this.txt_ApellidoVet = txt_ApellidoVet;
    }

    public JTextField getTxt_EspecialidadVet() {
        return txt_EspecialidadVet;
    }

    public void setTxt_EspecialidadVet(JTextField txt_EspecialidadVet) {
        this.txt_EspecialidadVet = txt_EspecialidadVet;
    }

    public JTextField getTxt_IDVet() {
        return txt_IDVet;
    }

    public void setTxt_IDVet(JTextField txt_IDVet) {
        this.txt_IDVet = txt_IDVet;
    }

    public JTextField getTxt_NomVet() {
        return txt_NomVet;
    }

    public void setTxt_NomVet(JTextField txt_NomVet) {
        this.txt_NomVet = txt_NomVet;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BusquedaFecha;
    private javax.swing.JComboBox<String> CBFechas;
    private javax.swing.JDialog DialogMascota;
    private javax.swing.JDialog DialogVeterinario;
    private javax.swing.JTable TablaRev;
    private javax.swing.JTable Tabla_Pacientes;
    private javax.swing.JTextArea Txt_Descripcion;
    private javax.swing.JTextArea Txt_enfermedad;
    private javax.swing.JButton btnAgregarRev;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarMasc;
    private javax.swing.JButton btnBuscarMed;
    private javax.swing.JButton btnCrearRev;
    private javax.swing.JButton btnEliminarRev;
    private javax.swing.JButton btnLimpiarRev;
    private javax.swing.JButton btnReporteImprimir;
    private javax.swing.JButton btn_AgregarMas;
    private javax.swing.JButton btn_AgregarMed;
    private javax.swing.JButton bttnImprimir;
    private javax.swing.JDialog dlgReporteRevision;
    private javax.swing.JDialog dlgRevision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lb_DescripcionR;
    private javax.swing.JLabel lb_DiagnosticoR;
    private javax.swing.JLabel lb_MascotaR;
    private javax.swing.JLabel lb_VeterinarioR1;
    private javax.swing.JLabel lblFotoMascotaRev;
    private javax.swing.JTable tbl_Veterinario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecieRev;
    private javax.swing.JTextField txtFechaRev;
    private javax.swing.JTextField txtIdclienteRev;
    private javax.swing.JTextField txtIdfacturaRev;
    private javax.swing.JTextField txtIdmascotaRev;
    private javax.swing.JTextField txtNombreMRev;
    private javax.swing.JTextField txtRazaRev;
    private javax.swing.JTextField txtReporteIdMedico;
    private javax.swing.JTextField txtReporteMascota;
    private javax.swing.JTextField txtReporteNombre;
    private javax.swing.JTextField txtSexoRev;
    private javax.swing.JTextField txt_ApellidoVet;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_ColorRev;
    private javax.swing.JTextField txt_EspecialidadVet;
    private javax.swing.JTextField txt_IDVet;
    private javax.swing.JTextField txt_NomVet;
    // End of variables declaration//GEN-END:variables
}
