/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Revision;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Edison
 */
public class ViewCrudRevision extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewCrudRevision
     */
    public ViewCrudRevision() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogMascota = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Pacientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        btn_AgregarMas = new javax.swing.JButton();
        DialogVeterinario = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Veterinario = new javax.swing.JTable();
        txtBuscar1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btn_AgregarMed = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIdmascotaRev = new javax.swing.JTextField();
        txtIdclienteRev = new javax.swing.JTextField();
        txtNombreMRev = new javax.swing.JTextField();
        txtRazaRev = new javax.swing.JTextField();
        txtSexoRev = new javax.swing.JTextField();
        txtEspecieRev = new javax.swing.JTextField();
        jdcFechaNacRev = new com.toedter.calendar.JDateChooser();
        jdcFechaIngRev = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        lblFotoMascotaRev = new javax.swing.JLabel();
        btnBuscarMasc = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        lb_MascotaR = new javax.swing.JLabel();
        txt_ColorRev = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRev = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFechaRev = new javax.swing.JTextField();
        btnAgregarRev = new javax.swing.JButton();
        btnLimpiarRev = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Txt_enfermedad = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Txt_Descripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtIdfacturaRev = new javax.swing.JTextField();
        lb_DescripcionR = new javax.swing.JLabel();
        lb_DiagnosticoR = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_IDVet = new javax.swing.JTextField();
        txt_NomVet = new javax.swing.JTextField();
        txt_ApellidoVet = new javax.swing.JTextField();
        txt_DireccVet = new javax.swing.JTextField();
        txt_EspecialidadVet = new javax.swing.JTextField();
        btnBuscarMed = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lb_VeterinarioR1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        DialogMascota.setBackground(new java.awt.Color(255, 255, 255));
        DialogMascota.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/salud.png"))); // NOI18N
        jLabel20.setText("PACIENTES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "CI Cliente", "Nombre", "Sexo", "Especie", "Raza", "Color", "Edad", "Fecha Ingreso", "Foto"
            }
        ));
        jScrollPane2.setViewportView(Tabla_Pacientes);

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel21.setText("BUSCAR:");

        btn_AgregarMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar-archivo.png"))); // NOI18N
        btn_AgregarMas.setText("Añadir");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_AgregarMas)
                        .addGap(46, 46, 46))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_AgregarMas))
                    .addComponent(jLabel21))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout DialogMascotaLayout = new javax.swing.GroupLayout(DialogMascota.getContentPane());
        DialogMascota.getContentPane().setLayout(DialogMascotaLayout);
        DialogMascotaLayout.setHorizontalGroup(
            DialogMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogMascotaLayout.setVerticalGroup(
            DialogMascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogMascotaLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DialogVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        DialogVeterinario.setResizable(false);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/veterinario.png"))); // NOI18N
        jLabel22.setText("VETERINARIO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Veterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Veterinario", "Nombre_Veterinario", "Apellido_Veterinario", "Direccion_Veterinario", "Especialidad"
            }
        ));
        jScrollPane3.setViewportView(tbl_Veterinario);

        jLabel23.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel23.setText("BUSCAR:");

        btn_AgregarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar-archivo.png"))); // NOI18N
        btn_AgregarMed.setText("Añadir");
        btn_AgregarMed.setBorderPainted(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_AgregarMed)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AgregarMed)
                    .addComponent(jLabel23))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DialogVeterinarioLayout = new javax.swing.GroupLayout(DialogVeterinario.getContentPane());
        DialogVeterinario.getContentPane().setLayout(DialogVeterinarioLayout);
        DialogVeterinarioLayout.setHorizontalGroup(
            DialogVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogVeterinarioLayout.setVerticalGroup(
            DialogVeterinarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogVeterinarioLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/mascota-amigable.png"))); // NOI18N
        jLabel4.setText("Mascota");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("ID MASCOTA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("ID CLIENTE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel8.setText("NOMBRE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText("RAZA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel10.setText("SEXO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel11.setText("ESPECIE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel12.setText("COLOR");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel14.setText("F. INGRESO ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        jPanel1.add(txtIdmascotaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, -1));
        jPanel1.add(txtIdclienteRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));
        jPanel1.add(txtNombreMRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));
        jPanel1.add(txtRazaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 210, -1));
        jPanel1.add(txtSexoRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, -1));
        jPanel1.add(txtEspecieRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, -1));
        jPanel1.add(jdcFechaNacRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 210, -1));
        jPanel1.add(jdcFechaIngRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel13.setText("F. NACIMIENTO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        lblFotoMascotaRev.setBackground(new java.awt.Color(0, 0, 0));
        lblFotoMascotaRev.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblFotoMascotaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 140, 170));

        btnBuscarMasc.setText("...");
        btnBuscarMasc.setBorderPainted(false);
        jPanel1.add(btnBuscarMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 36, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/pngegg (4).png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        lb_MascotaR.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_MascotaR.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(lb_MascotaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 120, 20));
        jPanel1.add(txt_ColorRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 210, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(244, 244, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaRev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID REVISION", "ID MEDICO", "ID MASCOTA", "NOMBRE MASCOTA", "FECHA REVISION", "DESCRIPCION", "ENFERMEDAD"
            }
        ));
        jScrollPane1.setViewportView(TablaRev);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 585, 230));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setText("FECHA:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 10, -1, -1));
        jPanel2.add(txtFechaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 6, 100, -1));

        btnAgregarRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/agregar.png"))); // NOI18N
        btnAgregarRev.setText("Agregar");
        btnAgregarRev.setBorderPainted(false);
        jPanel2.add(btnAgregarRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));

        btnLimpiarRev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/codigo-limpio.png"))); // NOI18N
        btnLimpiarRev.setText("LIMPIAR");
        btnLimpiarRev.setBorderPainted(false);
        jPanel2.add(btnLimpiarRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, -1, -1));

        Txt_enfermedad.setColumns(20);
        Txt_enfermedad.setRows(5);
        jScrollPane4.setViewportView(Txt_enfermedad);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 430, 94));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel24.setText("DESCRIPCIÓN");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 347, -1, -1));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel25.setText("DIAGNÓSTICO");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        Txt_Descripcion.setColumns(20);
        Txt_Descripcion.setRows(5);
        jScrollPane5.setViewportView(Txt_Descripcion);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 430, 89));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("ID REVISION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 10, -1, -1));
        jPanel2.add(txtIdfacturaRev, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 6, 100, -1));

        lb_DescripcionR.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_DescripcionR.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(lb_DescripcionR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 120, 20));

        lb_DiagnosticoR.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_DiagnosticoR.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(lb_DiagnosticoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 120, 20));
        jPanel2.add(txt_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("ID VETERINARIO");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel15.setText("NOMBRE");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel16.setText("APELLIDO");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel17.setText("DIRECCION");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel18.setText("ESPECIALIDAD");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));
        jPanel3.add(txt_IDVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 150, -1));
        jPanel3.add(txt_NomVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 250, -1));
        jPanel3.add(txt_ApellidoVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 250, -1));
        jPanel3.add(txt_DireccVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 250, -1));
        jPanel3.add(txt_EspecialidadVet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 250, -1));

        btnBuscarMed.setText("...");
        btnBuscarMed.setBorderPainted(false);
        jPanel3.add(btnBuscarMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 32, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/veterinario.png"))); // NOI18N
        jLabel19.setText("Veterinario");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/pngegg (2).png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 240));

        lb_VeterinarioR1.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lb_VeterinarioR1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.add(lb_VeterinarioR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 120, 20));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(126, 197, 68));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/buscando.png"))); // NOI18N
        jLabel3.setText("Revision");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextArea getTxt_Descripcion() {
        return Txt_Descripcion;
    }

    public JLabel getLb_DescripcionR() {
        return lb_DescripcionR;
    }

    public void setLb_DescripcionR(JLabel lb_DescripcionR) {
        this.lb_DescripcionR = lb_DescripcionR;
    }

    public JTextField getTxt_Buscar() {
        return txt_Buscar;
    }

    public void setTxt_Buscar(JTextField txt_Buscar) {
        this.txt_Buscar = txt_Buscar;
    }

    public JLabel getLb_DiagnosticoR() {
        return lb_DiagnosticoR;
    }

    public void setLb_DiagnosticoR(JLabel lb_DiagnosticoR) {
        this.lb_DiagnosticoR = lb_DiagnosticoR;
    }

    public JLabel getLb_MascotaR() {
        return lb_MascotaR;
    }

    public void setLb_MascotaR(JLabel lb_MascotaR) {
        this.lb_MascotaR = lb_MascotaR;
    }

    public JLabel getLb_VeterinarioR1() {
        return lb_VeterinarioR1;
    }

    public void setLb_VeterinarioR1(JLabel lb_VeterinarioR1) {
        this.lb_VeterinarioR1 = lb_VeterinarioR1;
    }
    
    
    public void setTxt_Descripcion(JTextArea Txt_Descripcion) {
        this.Txt_Descripcion = Txt_Descripcion;
    }

    public JTextArea getTxt_enfermedad() {
        return Txt_enfermedad;
    }

    public void setTxt_enfermedad(JTextArea Txt_enfermedad) {
        this.Txt_enfermedad = Txt_enfermedad;
    }

    public JLabel getjLabel24() {
        return jLabel24;
    }

    public void setjLabel24(JLabel jLabel24) {
        this.jLabel24 = jLabel24;
    }

    public JLabel getjLabel25() {
        return jLabel25;
    }

    public void setjLabel25(JLabel jLabel25) {
        this.jLabel25 = jLabel25;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public void setjScrollPane5(JScrollPane jScrollPane5) {
        this.jScrollPane5 = jScrollPane5;
    }

    public JDialog getDialogMascota() {
        return DialogMascota;
    }

    public void setDialogMascota(JDialog DialogMascota) {
        this.DialogMascota = DialogMascota;
    }

    public JDialog getDialogVeterinario() {
        return DialogVeterinario;
    }

    public void setDialogVeterinario(JDialog DialogVeterinario) {
        this.DialogVeterinario = DialogVeterinario;
    }

    public JTable getTablaRev() {
        return TablaRev;
    }

    public void setTablaRev(JTable TablaRev) {
        this.TablaRev = TablaRev;
    }

    public JTable getTabla_Pacientes() {
        return Tabla_Pacientes;
    }

    public void setTabla_Pacientes(JTable Tabla_Pacientes) {
        this.Tabla_Pacientes = Tabla_Pacientes;
    }

    public JButton getBtnAgregarRev() {
        return btnAgregarRev;
    }

    public void setBtnAgregarRev(JButton btnAgregarRev) {
        this.btnAgregarRev = btnAgregarRev;
    }

    public JButton getBtnBuscarMasc() {
        return btnBuscarMasc;
    }

    public void setBtnBuscarMasc(JButton btnBuscarMasc) {
        this.btnBuscarMasc = btnBuscarMasc;
    }

    public JButton getBtnBuscarMed() {
        return btnBuscarMed;
    }

    public void setBtnBuscarMed(JButton btnBuscarMed) {
        this.btnBuscarMed = btnBuscarMed;
    }

    public JButton getBtnLimpiarRev() {
        return btnLimpiarRev;
    }

    public void setBtnLimpiarRev(JButton btnLimpiarRev) {
        this.btnLimpiarRev = btnLimpiarRev;
    }


    public JButton getBtn_AgregarMas() {
        return btn_AgregarMas;
    }

    public void setBtn_AgregarMas(JButton btn_AgregarMas) {
        this.btn_AgregarMas = btn_AgregarMas;
    }

    public JButton getBtn_AgregarMed() {
        return btn_AgregarMed;
    }

    public void setBtn_AgregarMed(JButton btn_AgregarMed) {
        this.btn_AgregarMed = btn_AgregarMed;
    }



    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JLabel getjLabel15() {
        return jLabel15;
    }

    public void setjLabel15(JLabel jLabel15) {
        this.jLabel15 = jLabel15;
    }

    public JLabel getjLabel16() {
        return jLabel16;
    }

    public void setjLabel16(JLabel jLabel16) {
        this.jLabel16 = jLabel16;
    }

    public JLabel getjLabel17() {
        return jLabel17;
    }

    public void setjLabel17(JLabel jLabel17) {
        this.jLabel17 = jLabel17;
    }

    public JLabel getjLabel18() {
        return jLabel18;
    }

    public void setjLabel18(JLabel jLabel18) {
        this.jLabel18 = jLabel18;
    }

    public JLabel getjLabel19() {
        return jLabel19;
    }

    public void setjLabel19(JLabel jLabel19) {
        this.jLabel19 = jLabel19;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel20() {
        return jLabel20;
    }

    public void setjLabel20(JLabel jLabel20) {
        this.jLabel20 = jLabel20;
    }

    public JLabel getjLabel21() {
        return jLabel21;
    }

    public void setjLabel21(JLabel jLabel21) {
        this.jLabel21 = jLabel21;
    }

    public JLabel getjLabel22() {
        return jLabel22;
    }

    public void setjLabel22(JLabel jLabel22) {
        this.jLabel22 = jLabel22;
    }

    public JLabel getjLabel23() {
        return jLabel23;
    }

    public void setjLabel23(JLabel jLabel23) {
        this.jLabel23 = jLabel23;
    }


    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JDateChooser getJdcFechaIngRev() {
        return jdcFechaIngRev;
    }

    public void setJdcFechaIngRev(JDateChooser jdcFechaIngRev) {
        this.jdcFechaIngRev = jdcFechaIngRev;
    }

    public JDateChooser getJdcFechaNacRev() {
        return jdcFechaNacRev;
    }

    public void setJdcFechaNacRev(JDateChooser jdcFechaNacRev) {
        this.jdcFechaNacRev = jdcFechaNacRev;
    }

    public JLabel getLblFotoMascotaRev() {
        return lblFotoMascotaRev;
    }

    public void setLblFotoMascotaRev(JLabel lblFotoMascotaRev) {
        this.lblFotoMascotaRev = lblFotoMascotaRev;
    }

    public JTable getTbl_Veterinario() {
        return tbl_Veterinario;
    }

    public void setTbl_Veterinario(JTable tbl_Veterinario) {
        this.tbl_Veterinario = tbl_Veterinario;
    }

    public JTextField getTxtBuscar() {
        return txtBuscar;
    }

    public void setTxtBuscar(JTextField txtBuscar) {
        this.txtBuscar = txtBuscar;
    }

    public JTextField getTxtBuscar1() {
        return txtBuscar1;
    }

    public void setTxtBuscar1(JTextField txtBuscar1) {
        this.txtBuscar1 = txtBuscar1;
    }
   public JTextField getTxtEspecieRev() {
        return txtEspecieRev;
    }

    public JTextField getTxt_ColorRev() {
        return txt_ColorRev;
    }

    public void setTxt_ColorRev(JTextField txt_ColorRev) {
        this.txt_ColorRev = txt_ColorRev;
    }

    public void setTxtEspecieRev(JTextField txtEspecieRev) {
        this.txtEspecieRev = txtEspecieRev;
    }

    public JTextField getTxtFechaRev() {
        return txtFechaRev;
    }

    public void setTxtFechaRev(JTextField txtFechaRev) {
        this.txtFechaRev = txtFechaRev;
    }

    public JTextField getTxtIdclienteRev() {
        return txtIdclienteRev;
    }

    public void setTxtIdclienteRev(JTextField txtIdclienteRev) {
        this.txtIdclienteRev = txtIdclienteRev;
    }

    public JTextField getTxtIdfacturaRev() {
        return txtIdfacturaRev;
    }

    public void setTxtIdfacturaRev(JTextField txtIdfacturaRev) {
        this.txtIdfacturaRev = txtIdfacturaRev;
    }

    public JTextField getTxtIdmascotaRev() {
        return txtIdmascotaRev;
    }

    public void setTxtIdmascotaRev(JTextField txtIdmascotaRev) {
        this.txtIdmascotaRev = txtIdmascotaRev;
    }

    public JTextField getTxtNombreMRev() {
        return txtNombreMRev;
    }

    public void setTxtNombreMRev(JTextField txtNombreMRev) {
        this.txtNombreMRev = txtNombreMRev;
    }

    public JTextField getTxtRazaRev() {
        return txtRazaRev;
    }

    public void setTxtRazaRev(JTextField txtRazaRev) {
        this.txtRazaRev = txtRazaRev;
    }

    public JTextField getTxtSexoRev() {
        return txtSexoRev;
    }

    public void setTxtSexoRev(JTextField txtSexoRev) {
        this.txtSexoRev = txtSexoRev;
    }



    public JTextField getTxt_ApellidoVet() {
        return txt_ApellidoVet;
    }

    public void setTxt_ApellidoVet(JTextField txt_ApellidoVet) {
        this.txt_ApellidoVet = txt_ApellidoVet;
    }

    public JTextField getTxt_DireccVet() {
        return txt_DireccVet;
    }

    public void setTxt_DireccVet(JTextField txt_DireccVet) {
        this.txt_DireccVet = txt_DireccVet;
    }

    public JTextField getTxt_EspecialidadVet() {
        return txt_EspecialidadVet;
    }

    public void setTxt_EspecialidadVet(JTextField txt_EspecialidadVet) {
        this.txt_EspecialidadVet = txt_EspecialidadVet;
    }

    public JTextField getTxt_IDVet() {
        return txt_IDVet;
    }

    public void setTxt_IDVet(JTextField txt_IDVet) {
        this.txt_IDVet = txt_IDVet;
    }

    public JTextField getTxt_NomVet() {
        return txt_NomVet;
    }

    public void setTxt_NomVet(JTextField txt_NomVet) {
        this.txt_NomVet = txt_NomVet;
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogMascota;
    private javax.swing.JDialog DialogVeterinario;
    private javax.swing.JTable TablaRev;
    private javax.swing.JTable Tabla_Pacientes;
    private javax.swing.JTextArea Txt_Descripcion;
    private javax.swing.JTextArea Txt_enfermedad;
    private javax.swing.JButton btnAgregarRev;
    private javax.swing.JButton btnBuscarMasc;
    private javax.swing.JButton btnBuscarMed;
    private javax.swing.JButton btnLimpiarRev;
    private javax.swing.JButton btn_AgregarMas;
    private javax.swing.JButton btn_AgregarMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.calendar.JDateChooser jdcFechaIngRev;
    private com.toedter.calendar.JDateChooser jdcFechaNacRev;
    private javax.swing.JLabel lb_DescripcionR;
    private javax.swing.JLabel lb_DiagnosticoR;
    private javax.swing.JLabel lb_MascotaR;
    private javax.swing.JLabel lb_VeterinarioR1;
    private javax.swing.JLabel lblFotoMascotaRev;
    private javax.swing.JTable tbl_Veterinario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtEspecieRev;
    private javax.swing.JTextField txtFechaRev;
    private javax.swing.JTextField txtIdclienteRev;
    private javax.swing.JTextField txtIdfacturaRev;
    private javax.swing.JTextField txtIdmascotaRev;
    private javax.swing.JTextField txtNombreMRev;
    private javax.swing.JTextField txtRazaRev;
    private javax.swing.JTextField txtSexoRev;
    private javax.swing.JTextField txt_ApellidoVet;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_ColorRev;
    private javax.swing.JTextField txt_DireccVet;
    private javax.swing.JTextField txt_EspecialidadVet;
    private javax.swing.JTextField txt_IDVet;
    private javax.swing.JTextField txt_NomVet;
    // End of variables declaration//GEN-END:variables
}
