/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.MenuPrincipal;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class LoginVet extends javax.swing.JFrame {

    /**
     * Creates new form LoginVet
     */
    public LoginVet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelContraseña = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        label_Usuario = new javax.swing.JLabel();
        txtcontraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelContraseña.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(102, 102, 102));
        labelContraseña.setText("Contraseña:");
        jPanel1.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        txtusuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 260, 30));

        label_Usuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_Usuario.setForeground(new java.awt.Color(102, 102, 102));
        label_Usuario.setText("ID Usuario:");
        jPanel1.add(label_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        txtcontraseña.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        txtcontraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcontraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 260, 30));

        btnIniciarSesion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBorderPainted(false);
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 160, 50));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/Iconos/eliminar (2).png"))); // NOI18N
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesProyecto/portrait-collection-of-adorable-puppies.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnIniciarSesion() {
        return btnIniciarSesion;
    }

    public void setBtnIniciarSesion(JButton btnIniciarSesion) {
        this.btnIniciarSesion = btnIniciarSesion;
    }


    public JPasswordField getTxtcontraseña() {
        return txtcontraseña;
    }

    public void setTxtcontraseña(JPasswordField txtcontraseña) {
        this.txtcontraseña = txtcontraseña;
    }

    public JTextField getTxtusuario() {
        return txtusuario;
    }

    public void setTxtusuario(JTextField txtusuario) {
        this.txtusuario = txtusuario;
    }

    public JButton getSalir() {
        return Salir;
    }

    public void setSalir(JButton Salir) {
        this.Salir = Salir;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel label_Usuario;
    private javax.swing.JPasswordField txtcontraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
